### PR TITLE
Feature/display conflicting revisions

### PR DESCRIPTION
**Pull request by tleyden**
This PR is only to display the conflicting revisions to the user.  (reincarnation of https://github.com/couchbaselabs/ToDoLite-Android/pull/39)

### CODE REVIEW

**Comment by tleyden** [comment]
I ran into https://github.com/couchbase/couchbase-lite-java-core/issues/481 while testing, but I don't think it's related to this PR

**Comment by tleyden** [comment]
@jamiltz I tested this and found an issue.  Attaching an image using the genymotion emulator isn't working (whereas it works on the master branch)

Steps:

* Start in genymotion (nexus 4 api 19)
* Create new list
* Hit camera icon in "add new task"
* Take photo of black screen with genymotion icon
* Expected: should show thumbnail of photo
* Actual: shows nothing, the image seems to be discarded.

**Comment by jamiltz** [comment]
Ok will look into and fix it.

**Comment by jamiltz** [comment]
In the process of moving the TasksFragment class to its own file, I was getting a compiler error on this line https://github.com/couchbaselabs/ToDoLite-Android/blob/master/ToDoLite/src/main/java/com/couchbase/todolite/MainActivity.java#L665 and trying to make it compile by typing the int instead, incorrectly (https://github.com/couchbaselabs/ToDoLite-Android/commit/4b95e85876461f6f7552701ff0c9d71d1d8988ea#diff-4b3e9fef5816588cec5548ccd45b3d5fR357), it should have been -1. 

I changed the line to `getActivity.RESULT_OK` instead of trying to replace with the matching int. Fixed in the last commit, images are attached correctly now. Sorry for the delay.

**Pull request merged**
