### PR TITLE
Add conflict resolution

### PR DESCRIPTION
**Pull request by jamiltz**
User can pick the winning revision.

One issue I'm looking into: I believe live queries won't trigger the change event for non-current revisions. So when a client pulls non-current revisions, the conflict icon will stay invisible.

### CODE REVIEW

**Comment by Jamiltz** [comment]
Spent some time with @WilliamHoang reviewing the conflict resolution. There was a case when it would delete all the revisions but we think we fixed that in the last commit by storing the properties of the selected revision in a variable. That's how it works now http://cl.ly/ZzQz.

**Comment by pasin** [comment]
This looks cool.

**Comment by tleyden** [comment]
> There was a case when it would delete all the revisions but we think we fixed that in the last commit by storing the properties of the selected revision in a variable.

@Jamiltz there might be a better way.  Can you give a detailed explanation of why you need to do this?

**Comment by tleyden** [comment]
@Jamiltz see http://developer.couchbase.com/mobile/develop/guides/couchbase-lite/native-api/revision/index.html

Tombstoning

The reason that tombstone revisions exist is so that deletes can be sync'd to other databases. If revisions were simply deleted with a naive approach, then there would be no easy way to sync up with other databases that contained the revision.

There is a special field in a revision's JSON called _deleted which determines whether the revision is a tombstone revision or not. A consequence of this fact is that tombstone revisions can hold arbitrary amounts of metadata, which can be useful for an application. If the full metadata of the document is preserved in the tombstone revision, then a document could easily be restored to it's last known good state after it's been deleted at some point.

For examples of deleting revisions via adding a tombstone revision, refer to the guide on Documents.

**Comment by Jamiltz** [comment]
@pasin I believe so, except this occasional bug I'm trying to fix. New changes are in ListConflicts.java and ConflictsAdapter.java. Other changes were to move logic out of MainActivity into it's own adapter class.

@tleyden Actually it didn't fix the issue.
See https://github.com/couchbaselabs/ToDoLite-Android/pull/38/files?diff=unified#diff-9cc54b28d885c58e5be737157dea80beR65
This for-loop flags all non current revisions as deleted and creates a new revision with the selected userProperties. It works most of the time, but _sometimes_ it will just delete all revisions. I checked by adding breakpoints in the if/else and although it does call setUserProperties() and should create a new revision, it won't appear in the list of tasks. It's almost like it creates a new current revision but then this revision gets deleted.

*by delete, I always mean adding a tombstone revision.

**Comment by tleyden** [comment]
@Jamiltz what about separating this into two PR's?

* Remove the conflict resolution, and leave in the part that only lets users *view* conflicts and conflicting revisions
* 2nd PR that actually does conflict resolution

and in the 2nd PR we'll do a deeper dive on the problems you are seeing.

**Comment by Jamiltz** [comment]
@tleyden @pasin Good plan, will do that.

**Comment by jamiltz** [comment]
Closing this as it'll be split in two PRs instead.

**Pull request closed without merging**
